name: Trigger auto deployment for mwf-test-1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mwf-test-1-AutoDeployTrigger-c6842011-7175-4435-97ec-93b7903e8b58.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: workingacr.azurecr.io
          username: ${{ secrets.MWFTEST1_REGISTRY_USERNAME }}
          password: ${{ secrets.MWFTEST1_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: workingacr.azurecr.io/containerappsreactapptestz:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MWFTEST1_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mwf-test-1 -g test-environment --server workingacr.azurecr.io --username  ${{ secrets.MWFTEST1_REGISTRY_USERNAME }} --password ${{ secrets.MWFTEST1_REGISTRY_PASSWORD }}
            az containerapp update -n mwf-test-1 -g test-environment --image workingacr.azurecr.io/containerappsreactapptestz:${{ github.sha }}
